package com.visachecker.server.applications.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Applications")
public class Application {

    private String id;
    private String number;
    private String numberFake;
    private ApplicationCode code;
    private String year;

    public Application() {
    }

    public Application(String number, String numberFake, ApplicationCode code, String year) {
        this.number = number;
        this.numberFake = numberFake;
        this.code = code;
        this.year = year;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @DynamoDBAttribute
    public String getNumberFake() {
        return numberFake;
    }

    public void setNumberFake(String numberFake) {
        this.numberFake = numberFake;
    }

    @DynamoDBAttribute
    public ApplicationCode getCode() {
        return code;
    }

    public void setCode(ApplicationCode code) {
        this.code = code;
    }

    @DynamoDBAttribute
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }
}
