on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Set Gradle executable
        run: chmod +x ./VisaChecker.Server/gradlew    
      - name: Build with Gradle
        run: ./VisaChecker.Server/gradlew build --no-daemon