on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-server:
    defaults:
      run:
        working-directory: ./VisaChecker.Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
