on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-server:
    defaults:
      run:
        working-directory: ./VisaChecker.Server
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - name: Chmod ./gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          TAG: ${{ needs.get-version.outputs.tag }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/t6r8m9s8/visachecker-server:$TAG .
          docker push $REGISTRY/t6r8m9s8/visachecker-server:$TAG
  build-ui:
    defaults:
      run:
        working-directory: ./VisaChecker.UI
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: VisaChecker.UI/package-lock.json
      - name: Install project dependencies
        run: npm ci
      - run: npm run build
      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          TAG: ${{ needs.get-version.outputs.tag }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/t6r8m9s8/visachecker-ui:$TAG .
          docker push $REGISTRY/t6r8m9s8/visachecker-ui:$TAG